Dont center trajectory
2DegreesInvesting/r2dii.plot pull request #395
Opened 2021-09-24 14:27 UTC by MonikaFu

closes ADO [ticket 1907](https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/1907/)

In this PR I add a parameter that allows the user to choose whether the trajectory charts are centred around the starting value or not (in the current version of the package they were always centered).

2021-09-24 14:31 UTC, MonikaFu commented
@maurolepore this is still a draft version as I would like to hear your thoughts as to how to implement this feature. At the moment I added a parameter to `plot_trajectory()` that allows the user to switch off the centering. I am not sure if we should add this parameter to `qplot_trajectory()` as well. From theoretical point of view I would think not because it will make the plot less 'quick'. But then from what I've seen the usuers usually use the quick plots so forcing them to use the 'plot' in this case and doing all the data manipulations that quick plot does for them might not be the most-friendly approach. Curious to hear your thoughts.

2021-09-24 17:01 UTC, maurolepore reviewed
Here I share some comments about the implementation. 

I'll think a bit more about how to let the user control this behaviour. I need to refresh how we previously managed to allowed users to control behaviour whithout adding arguments. 

Will be back :)

2021-09-25 22:08 UTC, maurolepore reviewed
Okay, I reviewed the source code and noted we implemented features via arguments to the `prep_*()` functions. The `qplot_*()` functions call `prep_*()` with the argument that displays the most common behaviour and the `plot_*()` functions call `prep_*()` with the argument that displays the most vanilla behaviour. 

For example, `qplot_trajectory()` calls `prep_trajectory()` with `span_5yr = TRUE` and `plot_tajectory()` calls `prep_trajectory()` with `span_5yr = FALSE`. 

If we follow the same approach I think we should add the new argument (I suggest `center_y`) to `prep_tajectory()`, and `qplot_trajectory()` would use `TRUE` while `plot_trajectory()` would use `FALSE`. Does this sound right to you or is there a reason to take a different approach in this particular case?

One road we could take is to expose all arguments passed to `prep_plot()` but maybe only in `plot_trajectory()`. And then document how to use the arguments to match the `qplot_*()` functions. For example, `plot_trajectory()` would gain the argument `span_5yr` and its documentation would look like this:

```r
#' @param span_5yr Logical. Should the plot show only 5 yrs from the start date? 
#'   Use `TRUE` to get the behaviour of `qplot_trajectory()`.
```

That way it should be relatively easy to use `plot_*()` to get a plot like `qplot_*()` except for some feature they prefer turned off.

2021-09-27 09:22 UTC, MonikaFu commented
@maurolepore thanks for your comments, it all makes perfect sense. And actually, adding the argument to `prep_trajectory` will simplify significantly `plot_trajectory` I believe. Will work on implementation today.

2021-09-28 18:24 UTC, maurolepore reviewed
@MonikaFu, note the bug is now fixed. You may go ahead with this PR.

2021-09-28 18:24 UTC, maurolepore commented on R/plot_trajectory.R
> +  bind_rows(scenarios, not_scenarios)
The [error we got on CI](https://github.com/2DegreesInvesting/r2dii.plot/runs/3735392598?check_suite_focus=true) suggested the problem is that `dplyr::filter()` got a "matrix" or "list" (instead of a dataframe). Chasing the bug (with ubuntu 20.04 and R 3.6 at https://rstudio.cloud/project/1568984) I noticed that when `rbind()` takes one grouped dataframe it outputs a matrix -- not a dataframe. Replacing `rbind()` with `dplyr::bind_rows()` solved the problem. 

 
```r
no applicable method for 'filter' applied to an object of class "c('matrix', 'list')"
```

It would be nice to replace all instances of `rbind()` with `dplyr::bind_rows()` -- and in general prefer the safer tidyverse alternatives to base functions  (they exist for a reason).

--

This reprex shows that  before R 4.0 `rbind()` was not as smart as `dplyr::bind_rows()`:

``` r
R.version$version.string
#> [1] "R version 3.6.3 (2020-02-29)"

library(dplyr)

x <- data.frame(a = 1)
y <- data.frame(a = 1)

# OK
class(rbind(x, y))
#> [1] "data.frame"

x <- group_by(x, a)

# OK
class(bind_rows(x, y))
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"

# Bad
class(rbind(x, y))
#> [1] "matrix"
```

<sup>Created on 2021-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2021-09-29 08:54 UTC, MonikaFu commented on R/plot_trajectory.R
> +  bind_rows(scenarios, not_scenarios)
@maurolepore - thank you! I will be using `dplyr::bind_rows` from now on!

2021-09-29 09:16 UTC, MonikaFu commented
@maurolepore in commit d2725cf I replaced almost all instances of `rbind` by `bind_rows`. There is one function in `helper.R` in testthat folder still uses `rbind` (line 48 in tests/testthat/helper.R) as I was not sure of its functionality and didn't want to mess anything up. If you think that we should replace it there as well, let me know and I will. Or you go ahead.

2021-09-29 14:47 UTC, maurolepore requested changes
Thanks Monika!

- I hit request changes because I think there is  a small bug: Inside `plot_trajectory()` we need to pass the promise (not the value) to `prep_trajectory()` -- else the user won't be able to control the output from the top-level function. See my comment below.

Regarding our intention to export new arguments:

- I think we need to increment in the minor component of the version number.
- I think we need to engage Alex so he's aware of this significant change to the public interface.
- I think to we need to consider doing the same for all the `plot_*()` function, for consistency.

2021-09-29 14:47 UTC, maurolepore commented on R/plot_trajectory.R
>  }
If we expose the arguments in the signature of `plot_trajectory()`, then here we need to pass the name of the argument, not its value. If you hard code the value, then you loose the ability to control the behavior from the top-level function:

``` r
# Good
f <- function(x = 1) g(x = x)
g <- function(x = 1) x
f(2)
#> [1] 2

# Bad
f <- function(x = 1) g(x = 1)
g <- function(x = 1) x
f(2)
#> [1] 1
```

<sup>Created on 2021-09-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

--

Maybe write  a test to confirm the top-level function `plot_trajectory()` is indeed sensitive to changing the values of the arguments passed to `prep_trajectory()`.

2021-09-29 14:47 UTC, maurolepore commented on R/plot_trajectory.R
>  #' @noRd
If the arguments are documented in an exported function (`plot_trajectory()`), then it's best to not document them in the internal function (`prep_trajectory()`) -- that way we don't need to maintain the docs in two places.

2021-09-29 14:47 UTC, maurolepore commented on R/plot_trajectory.R
> +    filter(.data$year == min(data$year), is_portfolio(.data$metric)) %>%
`min()` defaults to `na.rm = FALSE`. What happens when the data has `NA`s? Do we have a test for it? 

https://github.com/2DegreesInvesting/r2dii.plot/issues/326

2021-09-29 14:47 UTC, maurolepore commented on R/plot_trajectory.R
> +        ),
Nit: I would either use the pipe or nested calls -- not a mix of both.

```r
# Pipe
f() %>% g() %>% h()
# Nest
h(g(f()))
# Mix
h(f() %>% g())
```

2021-09-29 14:47 UTC, maurolepore commented on tests/testthat/test-plot_trajectory.R
> +test_that("By default doesn't center the Y axis", {
For each new argument that we export I think we need to test the top-level function is sensitive to changes in that argument. 



``` r
library(testthat, warn.conflicts = FALSE)


# NEWS.md
# * `f()` gains the argument `x`.

# R/f.R
f <- function(x = TRUE) x

# tests/testthat/test-f.R
test_that("is sensitive to `x", {
  expect_true(f())
  expect_false(f(FALSE))
})
#> Test passed 🎊
```

<sup>Created on 2021-09-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2021-09-29 14:47 UTC, maurolepore commented on tests/testthat/test-plot_trajectory.R
> +})
It's hard to see that this code is doing what the test-title promises. Maybe use some intermediate variables to give meaningful names to pieces of code that capure relevant concepts such as `centered`, `not_centered`.

The idea is to try help the reader run the code in their heads. To better understand what's going on, they can always run the code but they should not have to.

2021-09-29 15:12 UTC, MonikaFu commented
@maurolepore - I am not sure what you mean by 'passing a promise'. Could you explain more?

2021-09-29 15:32 UTC, MonikaFu commented on R/plot_trajectory.R
> +plot_trajectory <- function(data, convert_label = identity, span_5yr = FALSE, center_y = FALSE) {
yes, your suggestion makes sense to do it for all other functions. I will put it in another issue and work on it separately, though, as I would like like to close this PR as Antoine needs this feature.

2021-09-29 15:34 UTC, maurolepore commented
Sorry Monika, I thought I had added a clarifying reprex but I didn't. Comming soon ...

2021-09-29 15:43 UTC, maurolepore commented
``` r
# Good:
# f_exported() passes to g_internal() the name that holds the value (promise)
f_exported <- function(x = 1) g_internal(x = x)  # Note x = x not x = 1
g_internal <- function(x = 1) x

# f_exported() is sensitive to changes in `x`
f_exported(1)
#> [1] 1
f_exported(2)
#> [1] 2
f_exported(3)
#> [1] 3



# Bad: 
# f_exported() passes to g_internal() a hard-coded value `1`
f_exported <- function(x = 1) g_internal(x = 1)
g_internal <- function(x = 1) x

# f_exported() is insensitive to changes in `x` -- it always returns `1`
f_exported(1)
#> [1] 1
f_exported(2)
#> [1] 1
f_exported(3)
#> [1] 1
```

<sup>Created on 2021-09-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2021-09-29 15:55 UTC, MonikaFu commented
@maurolepore Thanks for the example! I believe that my implementation was having the desired behaviour but now I made it more explicit.

2021-09-29 16:09 UTC, maurolepore approved these changes
LGTM. 

Thanks Monika, I see you addressed my main concern and are aware of my other suggestions. Go ahead and merge when you are ready.

2021-09-30 13:39 UTC, MonikaFu commented on R/plot_trajectory.R
> +plot_trajectory <- function(data, convert_label = identity, span_5yr = FALSE, center_y = FALSE) {
See #398

2021-09-30 14:38 UTC, merged