398 add parameters plot mll dry tests
2DegreesInvesting/r2dii.plot pull request #422
Opened 2021-10-13 19:13 UTC by maurolepore

- Change line types and colours (#418)
- DRY tests with a lil helper

2021-10-13 20:27 UTC, maurolepore commented on tests/testthat/test-scale_colour_r2dii.R
> +  expect_false(identical(colours_default, colours_changed))
Monika, did I interpret this expectation correctly?

2021-10-13 20:27 UTC, maurolepore commented on tests/testthat/test-plot_techmix.R
> +  expect_true(difference_is_letter_case(labels_def, labels_mod))
Monika, did I interpret this expectation correctly?

2021-10-14 12:04 UTC, MonikaFu commented on tests/testthat/test-plot_techmix.R
> +  expect_true(difference_is_letter_case(labels_def, labels_mod))
no, not necessarily, although in this case it will be. The point of this test is basically to check whether after passing a function modifying labels to `convert_label` paratemer we indeed get different labels. But whether the difference is letter case is not the point. If we passed a different function then the difference would be somethig else. So it is a wrong test in my opinion.

2021-10-14 12:08 UTC, MonikaFu requested changes

2021-10-14 12:08 UTC, MonikaFu commented on tests/testthat/test-plot_emission_intensity.R
> +  expect_true(difference_is_letter_case(labels_def, labels_mod))
This is not really correct. What I am testing for here is whether the labels differ from each other. I feel like formulating it this was draws attention away from what the test is acually about. But maybe I am wrong.

2021-10-14 12:08 UTC, MonikaFu commented on tests/testthat/test-plot_trajectory.R
> +  expect_false(diff(year_range(p_f)) == 5)
neat

2021-10-14 15:26 UTC, MonikaFu reviewed
LGTM. Thank you!

2021-10-14 15:45 UTC, merged